# This is a basic workflow to help you get started with Actions

name: Copy schema
env:
  targetBaseBranch: "main"
  fileName: "file"
  targetRepo: "mivanyna/repob"
  targetPathToFile: "folderb"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
permissions:
  contents: write
  pull-requests: write
  repository-projects: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      repository-projects: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.targetRepo }} target
          rm target/folderb/${{ env.fileName }}*.json
          
          cp "file.json" "./target/${{ env.targetPathToFile }}/${{ env.fileName }}_${{ github.sha }}.json"
          
          cd target
          git config --local user.email "${{ github.event.commits[0].committer.email }}"
          git config --local user.name "${{ github.event.commits[0].committer.name }}"
          git checkout ${{ env.targetBaseBranch }}
          git pull
          git checkout -b "${{ github.ref_name }}_${{ github.run_number }}"

          printf "const file = require('./${{ env.fileName }}_${{ github.sha }}.json')\nexport default file\n" > json.ts

          echo ${{ github.ref_name }}
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/project"
          echo "push"
          # git push -u origin "${{ github.ref_name }}_${{ github.run_number }}"
          echo "create PR"
          gh pr create -B "${{ env.targetBaseBranch }}" -H "${{ github.ref_name }}_${{ github.run_number }}" --title "${{ github.event.commits[0].message }}" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
